server:
  port: 8080

spring:
  application:
    name: film-service

  data:
    redis:
      host: redis
      port: 6379

  datasource:
    url: jdbc:mariadb://mariadb:3306/filmdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
