global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'film-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['film-service:8080']

  - job_name: 'review-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['review-service:8080']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
