global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'film-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['film-service:8081']
        labels:
          service: film-service
